matrix:
  include:
    - language: java
      jdk: openjdk8
      script:
        - mvn clean verify
cache:
  directories:
    - $HOME/.m2
notifications:
  slack:
    on_success: always
    on_failure: always
    on_error: always