#Default profile
server:
  port: 9000
spring:
  profiles:
    active: dev
auth:
  encoder:
    password: PtUwhwlBB4qcypKcy5z6TeX0gI8FbhMPtCEwJzMEO3k3kp0gVaExo0jxjR13ZczrjFmM4bnz19XsSi6JcseqiVYYtSHgwN9E9ZXg
    salt: 7a72815eaaea468012770bacd16a579ca44a6339
  repo:
    url: "http://localhost:3000"
    token: someToken
