#Default profile
server:
  port: 9000
spring:
  profiles:
    active: dev
auth:
  encoder:
    password: PtUwhwlBB4qcypKcy5z6TeX0gI8FbhMPtCEwJzMEO3k3kp0gVaExo0jxjR13ZczrjFmM4bnz19XsSi6JcseqiVYYtSHgwN9E9ZXg
    salt: 7a72815eaaea468012770bacd16a579ca44a6339
  jwt:
    secret: kxpQ4g5vmuQN6XqYVqLbg55ckZVBu3EkhPpY8r7hZgVciLKG0DGi0ZYn3Ua4qTZonbvcPr44CbizwHBMt5LonGSMrx3OCixBFLyVyG8ABsygpIeJOv3rwWEh6TSLPYFgLXN3KTRh2ZUbEAWFqgKOOXlURJnzpx4UaeeWhNdnw4gJ0AvIKFQjy2d8HW6SBussyIDKL2GU
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC9p6rmTb8HbYTRFzsPPARNnPrrpmT2cIVLA9R/uDXWHC1cq6c6fzLaxD+T2SUcBEpgY9O81kmU9/aOM+nJFIMHUc9Bga7rHSaOigd2IJ8do/UVcMj7VPdD3iicQ3hn/GEHHybK35aHRSfzP3H67wWRBrGcA0PU8iN0YKHf/Y7B1Q== max@webtree.org
    privateKey: >
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAIEAvaeq5k2/B22E0Rc7DzwETZz666Zk9nCFSwPUf7g11hwtXKunOn8y
          2sQ/k9klHARKYGPTvNZJlPf2jjPpyRSDB1HPQYGu6x0mjooHdiCfHaP1FXDI+1T3Q94onE
          N4Z/xhBx8myt+Wh0Un8z9x+u8FkQaxnAND1PIjdGCh3/2OwdUAAAIID+UO+g/lDvoAAAAH
          c3NoLXJzYQAAAIEAvaeq5k2/B22E0Rc7DzwETZz666Zk9nCFSwPUf7g11hwtXKunOn8y2s
          Q/k9klHARKYGPTvNZJlPf2jjPpyRSDB1HPQYGu6x0mjooHdiCfHaP1FXDI+1T3Q94onEN4
          Z/xhBx8myt+Wh0Un8z9x+u8FkQaxnAND1PIjdGCh3/2OwdUAAAADAQABAAAAgHDR7x41nb
          ADfIENurpjT4QEIFhSkbjwUrq/OogHwy7tcCayjjaEOHJfUBrZj/PMsZoJiInLR9Zwc6FA
          TJCrvQ11YaeqXykr1fe2hd628S8GAaQ5lqKSf0qJChNVPy0zmafp2rts9doZT5/kIUF5+3
          9zq6GpxaKwmf2XvE+SgNp5AAAAQCmqiKAxU5jUaq0kM5ldm9pv2aIlxeWNDLjaGR75oGUL
          nx6wA/Q/GTUSB8kyVpNpKtap5jfowkzBBFwEVFi1TKYAAABBAOKAuuP0pcnU+QVMHHjBI9
          6tIiaVm9G47GC054Hwxa7LKgraoaSsRlUiesKQymhWHH6kXyJ6Km3NwGLDeymRj0MAAABB
          ANZae6nAf7Ha56KqHJhvw7HQTtTTfRSgNvHK4USUcuNcWDd9TyWa5cmYpLU9FUsfBee7Jf
          cNez//7kOlAe6N3QcAAAAPbWF4QHdlYnRyZWUub3JnAQIDBA==
          -----END OPENSSH PRIVATE KEY-----

  repo:
    url: "http://localhost:3000"
    token: someToken
