#Default profile
server:
  port: 9000
spring:
  profiles:
    active: dev
auth:
  encoder:
    password: PtUwhwlBB4qcypKcy5z6TeX0gI8FbhMPtCEwJzMEO3k3kp0gVaExo0jxjR13ZczrjFmM4bnz19XsSi6JcseqiVYYtSHgwN9E9ZXg
    salt: 7a72815eaaea468012770bacd16a579ca44a6339
  jwt:
    secret: kxpQ4g5vmuQN6XqYVqLbg55ckZVBu3EkhPpY8r7hZgVciLKG0DGi0ZYn3Ua4qTZonbvcPr44CbizwHBMt5LonGSMrx3OCixBFLyVyG8ABsygpIeJOv3rwWEh6TSLPYFgLXN3KTRh2ZUbEAWFqgKOOXlURJnzpx4UaeeWhNdnw4gJ0AvIKFQjy2d8HW6SBussyIDKL2GU
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArFwVKY/NxPoek22zJ5enT9t+wdQyk432PT+0zBi7nx41tFnWRf24pw192hZ2Xkl+ioyp0kqNhML2YdUhCglyNH7RhzD6qUgKs2ZkYqKQ9m5pl4mE19rw5ScCF6m4yjdB4fq2sWnsKCu5GsvexHKsjlQ3OJMdzDzJlmvGbiwOk8KcFancmmhYlEGWT7V48MAS6QsWgDu1ZrvL1vbxbPnS+mQRbA4+dWAqgW3S2jjQAdeMzxWtymf4XKf2ULcGtsLtfPzjHZGHlYjaVp0q6mGx4HAsYEdptne8gMoEfuxIrbSQPRMeFB0yeCe2WIOEzmfn6wo5iwkGJ8m0XyTRulQhSwIDAQAB
    private_key: MIIDdzCCAl+gAwIBAgIEDCnKxTANBgkqhkiG9w0BAQsFADBsMRAwDgYDVQQGEwdVbmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYDVQQKEwdVbmtub3duMRAwDgYDVQQLEwdVbmtub3duMRAwDgYDVQQDEwdVbmtub3duMB4XDTE5MDkwNDAxMTA0NFoXDTE5MTIwMzAxMTA0NFowbDEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEQMA4GA1UEChMHVW5rbm93bjEQMA4GA1UECxMHVW5rbm93bjEQMA4GA1UEAxMHVW5rbm93bjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKxcFSmPzcT6HpNtsyeXp0/bfsHUMpON9j0/tMwYu58eNbRZ1kX9uKcNfdoWdl5JfoqMqdJKjYTC9mHVIQoJcjR+0Ycw+qlICrNmZGKikPZuaZeJhNfa8OUnAhepuMo3QeH6trFp7CgruRrL3sRyrI5UNziTHcw8yZZrxm4sDpPCnBWp3JpoWJRBlk+1ePDAEukLFoA7tWa7y9b28Wz50vpkEWwOPnVgKoFt0to40AHXjM8Vrcpn+Fyn9lC3BrbC7Xz84x2Rh5WI2ladKuphseBwLGBHabZ3vIDKBH7sSK20kD0THhQdMngntliDhM5n5+sKOYsJBifJtF8k0bpUIUsCAwEAAaMhMB8wHQYDVR0OBBYEFOuezwiSFBNffXRFVLGSM0POIee/MA0GCSqGSIb3DQEBCwUAA4IBAQB6AjMS/MVfnoiJ8FH7DyDuy37P+gDw6hBnJUnd3Y9EvlQyxih98DH5nufeP7Bny1pThH06ihs/EjJitcTq+P8/V6odpF928/zGEMx+PS+Uu7tEXO+G5gCheE/LhNMzNHB0BR0UikoomCrwkbfJfLeUl5MHCP/E72s/sKkMWduTeO0hgFwSZiui7slFQpSZqw5pEZyDrsIUOBpQz2N65u1+w2/MF+cyF84+M5ecC4qlTufIzm5tu1wl1HI09xH2ZGV69LdNw7qczX3r4PJ7aNwIR3xFqEp/Gn5DqgzLuB6abqfTw9JdaCtSqpmVsdEZrx5RguAs5fM/JPuq95GPYAKL
  repo:
    url: "http://localhost:3000"
    token: someToken
