#Default profile
server:
  port: 9000
spring:
  profiles:
    active: dev
  data:
    cassandra:
      keyspace-name: auth_main
      port: 9142
      contact-points: localhost
auth:
  encoder:
    password: 54679459
    salt: abccab