apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command: ['cat']
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
