auth:
  auth-details-impl: org.webtree.auth.domain.AuthDetailsImpl
  jwt:
    expiration: 604800
    header: Authorization
    secret: mySecret
  encoder:
    salt: 9e0b5328c644e94c
    password: passwordToChange
  route:
     login: /rest/token/new
     social-login: /rest/social/login
     register: /rest/user/register
  frontend-origin: "https://*.webtree.org"
#  wt-user-impl: org.webtree.auth.domain.WTUserDetailsImpl