auth:
  auth-details-impl: org.webtree.auth.domain.AuthDetailsImpl
  jwt:
    expiration: 604800
    header: Authorization
    secret: mySecret
  route:
     login: /rest/token/new
     social-login: /rest/social/login
     register: /rest/user/register
  frontend-origin: "https://*.webtree.org"