name: Auth API deploy

on:
  push:
    branches: 
      - master
      - api-deploy
    paths:
      - .github/workflows/api-deploy.yml
      - ./backend/auth-api
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Generate version name
        id: release-version
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              return 'auth-api-' + ${{ github.run_number }};

      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v3.1
        with:
          image: webtree/auth
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          directory: ./backend/auth-api
          dockerfile: ./backend/auth-api/Dockerfile
          tag: ${{ steps.release-version.outputs.result }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-version.outputs.result }}
          release_name: ${{ steps.release-version.outputs.result }}
          draft: false
          prerelease: false
      
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      
      - name: Upgrade helm chart
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: | 
            cd .k8s/chart
            helm repo add stable https://kubernetes-charts.storage.googleapis.com
            helm repo update
            helm dependency update
            helm upgrade auth . -n webtree --set image.tag=${{ steps.release-version.outputs.result }}
